[package]
name = "executor"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anyhow = "1"
jam-node = { path = "../../vendor/polkajam/crates/node", default-features = false, features = ["hazmat"] }
jam-types = { path = "../../vendor/polkajam/crates/jam-types", features = ["std"] }
