[package]
name = "frameless"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
codec = { workspace = true }
tiny-keccak = { workspace = true }
sp-io = { workspace = true }
parachain-service-interface = { workspace = true }

[target.'cfg(target_arch = "riscv64")'.dependencies]
polkavm-derive = { workspace = true }
sp-io = { workspace = true, features = ["disable_allocator", "disable_panic_handler"] }

[features]
default = [
	"std",
]
std = [
	"codec/std",
	"parachain-service-interface/std",
	"sp-io/std",
	"substrate-wasm-builder",
]

[build-dependencies]
substrate-wasm-builder = { workspace = true, optional = true }

[lints]
workspace = true
