[package]
name = "parachain-authorizer-ed25519"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
jam-types = { workspace = true }
jam-pvm-common = { workspace = true, features = ["authorizer", "logging"] }
parachain-authorizer = { workspace = true }
polkavm-derive = { workspace = true }
ed25519-dalek = { workspace = true, features = ["alloc"] }

[features]
std = [
	"ed25519-dalek/std",
	"jam-pvm-common/std",
	"jam-types/std",
	"parachain-authorizer/std",
]
