[package]
name = "parasim-tool"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "parasim-tool"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
codec = { workspace = true, features = ["std"] }
cumulus-jam-interface = { workspace = true }
cumulus-jam-rpc-interface = { workspace = true }
futures = { workspace = true }
jam-codec = { workspace = true, features = ["std"] }
jam-bootstrap-service-common = { workspace = true }
jam-null-authorizer-bin = { workspace = true }
jam-state-helpers = { workspace = true, features = ["std"] }
jam-std-common = { workspace = true }
jam-types = { workspace = true, features = ["std"] }
parachain-authorizer = { workspace = true, features = ["std"] }
parachain-service-interface = { workspace = true, features = ["std"] }
parasim-service = { workspace = true }
primitive-types = { workspace = true, features = ["std"] }
sp-core = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
