[package]
name = "jam-interface"
description = "Traits a Cumulus collator uses to talk to a JAM node"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
futures = { workspace = true }
jam-codec = { workspace = true, features = ["std"] }
jam-std-common = { workspace = true }
jam-types = { workspace = true, features = ["std"] }
